CxIAST integration documentation
checkmarx-ltd/cx-flow pull request #724
Opened 2021-05-10 09:49 UTC by yevgenykuz

### Description

CxIAST integration documentation. See #723 for actual code.

### References

#723 - actual code.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2021-05-10 09:53 UTC, cxflowtestuser commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 1412 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**44 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1262 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**106 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**10** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1059533&projectid=2118)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[67](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L67) [70](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L70) [71](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L71) [76](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L76) [78](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L78) [137](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/FlowController.java#L137) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1059533&projectid=2118&pathid=23)
[213](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/utils/ScanUtils.java#L213) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/utils/ScanUtils.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1059533&projectid=2118&pathid=7)
[100](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L100) [242](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/controller/GitHubController.java#L242) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/GitHubController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1059533&projectid=2118&pathid=11)
[60](https://github.com/checkmarx-ltd/cx-flow/blob/iast-docs/src/main/java/com/checkmarx/flow/service/ExternalScriptService.java#L60) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/service/ExternalScriptService.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1059533&projectid=2118&pathid=50)

2021-05-11 21:42 UTC, jbrotsos requested changes

2021-05-11 21:42 UTC, jbrotsos commented on docs/CxIAST-Integration.md
> +* [Suggested Flow](#suggestedFlow)
Rename Suggested Flow to "Overview"

2021-05-11 21:42 UTC, jbrotsos commented on docs/CxIAST-Integration.md
> +* [Suggested Flow](#suggestedFlow)
Filename should be "CxIAST Integration"

2021-05-11 21:42 UTC, jbrotsos commented on docs/CxIAST-Integration.md
> +CxIAST scans can be stopped in two ways:
CxIAST can be integrated within a CI/CD pipeline using CxFlow.  CxIAST scans start automatically when an application with an attached CxIAST agent is being tested.  To attach a CxIAST agent, please follow the following steps: [Insert steps here].
  
CxIAST scans can be stopped in two ways:

2021-05-11 21:42 UTC, jbrotsos commented on docs/CxIAST-Integration.md
> +To make sure the correct scan is stopped by CxFlow, CxIAST scan tags are used:
Onces tests are completed, CxFlow is used to stop the running CxIAST scan.  CxFlow will then collect the results from CxIAST, analyze them, and open tasks/tickets in the configured Bug Tracker [put link to Bug Tracker here].  To make sure the correct scan is stopped by CxFlow, CxIAST scan tags are used

2021-05-11 21:42 UTC, jbrotsos commented on docs/CxIAST-Integration.md
> +The filtering is done by vulnerability severity.
CxFlow filters CxIAST vulnerabilities by severity before creating bug tracker tickets.

2021-06-02 00:11 UTC, jbrotsos approved these changes

2021-06-02 00:12 UTC, jbrotsos commented
@yevgenykuz to get the tests to run, the branch name has to begin with pr-

2021-06-08 09:43 UTC, yevgenykuz commented
Closing in favor of #754.

2021-06-08 09:43 UTC, closed without merging