Slack bug tracker
checkmarx-ltd/cx-flow pull request #962
Opened 2022-03-17 17:23 UTC by cx-leonelsanches

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](https://github.com/checkmarx-ltd/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/checkmarx-ltd/open-source-template/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

Implementation of Slack Bug Tracker for a client.

### References

N/A

### Testing

- In a Slack workspace, create a Bot with the following OAuth scopes:
    - [channels:join](https://api.slack.com/scopes/channels:join)
    - [chat:write](https://api.slack.com/scopes/chat:write)
    - [chat:write.customize](https://api.slack.com/scopes/chat:write.customize)
    - [chat:write.public](https://api.slack.com/scopes/chat:write.public)
- Provide the generated token in `application.yml`
- Provide any additional configurations for Slack, such as channel name or, if required, a Slack Channel Script (Groovy)
- Register Slack as a custom Bug Tracker;
- While running CxFlow, trigger a scan using your favorite method. Check if at the end of the scan a notification is sent in a Slack channel. 

### Checklist

- [X] I have added documentation for new/changed functionality in this PR (if applicable).  *If documentation is a Wiki Update, please indicate desired changes within PR MD Comment*
- [X] All active GitHub checks for tests, formatting, and security are passing
- [X] The correct base branch is being used
- [X] Verified that SCA and SAST scan results are as expected

2022-03-17 17:24 UTC, cxflowtestuser commented
Scan submitted to Checkmarx

2022-03-17 17:30 UTC, cxflowtestuser commented
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)<br />**Checkmarx SAST - Scan Summary & Details**
### Cx-SAST Summary
Total of 2313 vulnerabilities<br />![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**0 High**<br />![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**5 Medium**<br />![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**2198 Low**<br />![Info](https://user-images.githubusercontent.com/23239410/92157090-97c0ec80-ee32-11ea-9b2e-aa6b32b03d54.png)&nbsp;**110 Info**<br />
### Violation Summary
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**4** **Medium**<br />
[View more details on Checkmarx UI](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1100497&projectid=5956)
### Cx-SAST Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[90](https://github.com/checkmarx-ltd/cx-flow/blob/slack-bug-tracker/src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java#L90) |Medium|Unchecked_Input_for_Loop_Condition|src/main/java/com/checkmarx/flow/controller/bitbucket/cloud/BitbucketCloudController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1100497&projectid=5956&pathid=26)
[81](https://github.com/checkmarx-ltd/cx-flow/blob/slack-bug-tracker/src/main/java/com/checkmarx/flow/custom/SlackIssueTracker.java#L81) |Medium|Privacy_Violation|src/main/java/com/checkmarx/flow/custom/SlackIssueTracker.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1100497&projectid=5956&pathid=30)
[72](https://github.com/checkmarx-ltd/cx-flow/blob/slack-bug-tracker/src/main/java/com/checkmarx/flow/controller/FlowController.java#L72) [75](https://github.com/checkmarx-ltd/cx-flow/blob/slack-bug-tracker/src/main/java/com/checkmarx/flow/controller/FlowController.java#L75) |Medium|Input_Path_Not_Canonicalized|src/main/java/com/checkmarx/flow/controller/FlowController.java|[Checkmarx](https://sast.checkmarx.net/CxWebClient/ViewerMain.aspx?scanid=1100497&projectid=5956&pathid=1)
***
![Logo](https://user-images.githubusercontent.com/23239410/92153465-ff743900-ee2c-11ea-9c8d-8141e38feb41.png)
**Checkmarx SCA - Scan Summary & Details**
### Cx-SCA Summary
**Total Packages Identified**: **267**
**Scan Risk Score**: **9.80**

![High](https://user-images.githubusercontent.com/23239410/92157087-97285600-ee32-11ea-988f-0aca12c4c126.png)&nbsp;**4** **High** **severity vulnerabilities**
![Medium](https://user-images.githubusercontent.com/23239410/92157093-98598300-ee32-11ea-83d7-af52251a011b.png)&nbsp;**0** **Medium** **severity vulnerabilities**
![Low](https://user-images.githubusercontent.com/23239410/92157091-98598300-ee32-11ea-8498-19bd7d62019b.png)&nbsp;**1** **Low** **severity vulnerabilities**
[View more details on Checkmarx UI](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff)
### Cx-SCA vulnerability result overview
|Vulnerability ID|Package|Severity|CVSS score|Publish date|Current version|Recommended version|Link in CxSCA|Reference – NVD link|
---|---|---|---|---|---|---|---|---
`CVE-2016-1000031`|commons-fileupload:commons-fileupload|HIGH|9.8|2016-10-25T14:29:00|1.0|| [Vulnerability Link](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff/vulnerabilities/CVE-2016-1000031%3AMaven-commons-fileupload%3Acommons-fileupload-1.0/vulnerabilityDetails)|[CVE-2016-1000031](https://nvd.nist.gov/vuln/detail/CVE-2016-1000031)
`CVE-2016-3092`|commons-fileupload:commons-fileupload|HIGH|7.5|2016-07-04T22:59:00|1.0|| [Vulnerability Link](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff/vulnerabilities/CVE-2016-3092%3AMaven-commons-fileupload%3Acommons-fileupload-1.0/vulnerabilityDetails)|[CVE-2016-3092](https://nvd.nist.gov/vuln/detail/CVE-2016-3092)
`CVE-2014-0050`|commons-fileupload:commons-fileupload|HIGH|7.5|2014-04-01T06:27:00|1.0|| [Vulnerability Link](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff/vulnerabilities/CVE-2014-0050%3AMaven-commons-fileupload%3Acommons-fileupload-1.0/vulnerabilityDetails)|[CVE-2014-0050](https://nvd.nist.gov/vuln/detail/CVE-2014-0050)
`CVE-2013-2186`|commons-fileupload:commons-fileupload|HIGH|7.5|2013-10-28T21:55:00|1.0|| [Vulnerability Link](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff/vulnerabilities/CVE-2013-2186%3AMaven-commons-fileupload%3Acommons-fileupload-1.0/vulnerabilityDetails)|[CVE-2013-2186](https://nvd.nist.gov/vuln/detail/CVE-2013-2186)
`CVE-2013-0248`|commons-fileupload:commons-fileupload|LOW|3.3|2013-03-15T20:55:00|1.0|| [Vulnerability Link](https://eu.sca.checkmarx.net/#/projects/dc7bfc48-fc75-46a3-a7ec-1a971be755a8/reports/b13d25df-0718-4aef-bc62-c743ed237aff/vulnerabilities/CVE-2013-0248%3AMaven-commons-fileupload%3Acommons-fileupload-1.0/vulnerabilityDetails)|[CVE-2013-0248](https://nvd.nist.gov/vuln/detail/CVE-2013-0248)

2022-03-21 06:20 UTC, umeshwaghode requested changes
Change files count is very high and it is merely because of spaces.  Please clean it up.
Also, there are some vulnerabilities reported in new classes introduced.

2022-03-21 23:19 UTC, cx-leonelsanches commented
Hi @umeshwaghode,

The files were modified by IntelliJ's automatic formatting. I also reorganized the properties into an unified package, hence the number, but you can review all of them quickly. 

Regarding the vulnerability, I can't access the CxSAST instance that scans here: 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/86265009/159378555-ac83ca80-311b-4cf6-8eb4-f9bb75449eab.png">

Can you please help me with this?

2022-08-19 22:32 UTC, cx-leonelsanches commented
Abandoning Slack as a Bug Tracker. Implementing as a Feedback Channel instead: https://github.com/checkmarx-ltd/cx-flow/pull/1092

2022-08-19 22:32 UTC, closed without merging